### ISSUE TITLE
style tags not needed in $style here-string

### ISSUE THREAD

**Issue by chadmando** [devops-collective-inc/creating-html-reports-in-powershell#3]
Firstly. Thank you @concentrateddon for the Powershell learning content, it has been very helpful in building my skills. While working through the book, I found a minor issue.

In the EnhancedHTML2 module, the -CSSStyleSheet parameter wraps the assigned variable in opening/closing style tags.

from lines 120-121 of  EnhancedHTML2.psm1:

`if ($PSBoundParameters.ContainsKey('CssStyleSheet')) {
        $stylesheet = "<style>$CssStyleSheet</style>" | Out-String`

It seems that including those same tags in the here-string assigned to $style wouldn't be necessary.

The final result of working through the book example is a double set of opening/closing tags.  That doesn't cause any performance issues with the CSS so it could be ignored.  

I would be happy to submit a PR for the fix if you think it needs to be addressed.  

Thanks again.

**Comment by concentrateddon** [comment]
Please do submit a PR. Best way to help out!! And thank you!

Sent from my iPhone

On Jun 26, 2018, at 2:49 PM, chadmando <notifications@github.com<mailto:notifications@github.com>> wrote:


Firstly. Thank you @concentrateddon<https://github.com/concentrateddon> for the Powershell learning content, it has been very helpful in building my skills. While working through the book, I found a minor issue.

In the EnhancedHTML2 module, the -CSSStyleSheet parameter wraps the assigned variable in opening/closing style tags.

from lines 120-121 of EnhancedHTML2.psm1:

if ($PSBoundParameters.ContainsKey('CssStyleSheet')) { $stylesheet = "<style>$CssStyleSheet</style>" | Out-String

It seems that including those same tags in the here-string assigned to $style wouldn't be necessary.

The final result of working through the book example is a double set of opening/closing tags. That doesn't cause any performance issues with the CSS so it could be ignored.

I would be happy to submit a PR for the fix if you think it needs to be addressed.

Thanks again.
